### PR TITLE
User can view all diary that have recorded

### PR DESCRIPTION
**Pull request by panitnt**
Add a link to index page that user can choose day to see a old diary.

### CODE REVIEW

**Review by natekrth — CHANGES_REQUESTED** [review]
May I adjust components in mood_sort.html?

**Comment by panitnt** [comment]
> May I adjust components in mood_sort.html?

Sure, go ahead!

**Comment by natekrth** [comment]
Done. Please review it again. Thanks

**Review by natekrth — APPROVED** [review]
Good to go...

**Review by teenteennnii — APPROVED** [review]
Good

**Review by sivazzer — APPROVED** [review]
Approved

**Pull request merged**
