### PR TITLE
Link Oauth with main feature

### PR DESCRIPTION
**Pull request by panitnt**
Implement login required for all features in mood by create new models.

### CODE REVIEW

**Comment by natekrth** [comment]
Reviewing...

**Comment by natekrth** [comment]
May you remove input.css and tailwind.config.js file please?

**Review by natekrth — APPROVED** [review]
Approved. Code and authentication to use each feature looks fine for now. Great work!

**Review by teenteennnii — APPROVED** [review]
Approved

**Review by teenteennnii — CHANGES_REQUESTED** [review]
After login, in page home and record will error.

**Review by teenteennnii — APPROVED** [review]

**Review by teenteennnii — APPROVED** [review]

**Review by natekrth — APPROVED** [review]
Approved. Good to go

**Comment by panitnt** [comment]
> After login, in page home and record will error.

Maybe you delete your old database, and migrate again.

**Pull request merged**
