### PR TITLE
Mood discover

### PR DESCRIPTION
**Pull request by panitnt**
We mainly implement mood discover page on this branch
so we have already finished
1.  Design and implement discover page layout
2. Calculation of average sleep time
3. Sleep time bar chart
4. Weather bar chart
5. Find top 3 people from each mood
6. Fine top 3 place from each mood

Please carefully review on discover.html and  mood/views.py
Thank you. ^^

### CODE REVIEW

**Review by natekrth — CHANGES_REQUESTED** [review]
Just suggest that tailwind.config.js and input.css may not need

**Review by teenteennnii — APPROVED** [review]
Appoved

**Review by sivazzer — APPROVED** [review]
Approved.

**Review by natekrth — APPROVED** [review]
Approved. Thank you

**Pull request merged**
